steps:
- id: 'Run Unit Tests'
  name: golang:1.18
  entrypoint: /bin/bash
  args: 
    - -c
    - |
      go test

- id: 'Build and push image'
  name: 'gcr.io/k8s-skaffold/skaffold:v1.39.2'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    skaffold build \
    --interactive=false \
    --default-repo us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique \
    --file-output artifacts.json

# - name: 'gcr.io/k8s-skaffold/pack'
#   entrypoint: 'pack'
#   args: ['build', '--builder=gcr.io/buildpacks/builder', '--publish', 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/productcatalogservice:$SHORT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - > 
    gcloud deploy releases create release-$BUILD_ID
    --delivery-pipeline=productcatalogservice
    --region=us-central1
    --source=./
    --images=productcatalogservice=us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique/productcatalogservice:$SHORT_SHA 

timeout: '3600s'