---
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: productcatalogservice
description: Product Catalog Service Deployment Pipeline 
serialPipeline:
  stages:
  - targetId: staging
  - targetId: production

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: staging
description: Staging Environment
gke:
  cluster: projects/ivory-setup-362907/locations/southamerica-east1/clusters/staging

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: production
description: Production Environment
gke:
  cluster: projects/ivory-setup-362907/locations/us-west1/clusters/prod